ValueWith/ValueWith_FE

package-lock.json, package.json, src/components/group/recruit/GroupItemCard/index.tsx, src/components/group/recruit/GroupRegistSchedule/index.tsx, src/main.tsx
- 드래그 앤 드랍 기능 추가
- 드래그 앤 드랍으로 인한 카드 컴포넌트 조건문 추가
=> Drag and drop

src/assets/styles/GlobalStyles.tsx
- html에 user-agent 스타일로 line-height가 지정되어있는 것을 확인하고 전역 스타일에 줄높이 지정
=> Fix : 공통 컴포넌트를 시안과 동일하게 보이도록 수정

src/assets/styles/GlobalStyles.tsx, src/components/Header/Header.styles.ts, src/components/Header/index.tsx, src/constants/pagelink.ts
- 로그아웃 버튼 추가
- window.location.reload가 그룹 페이지에서만 동작하도록 조건문 추가
=> Feat : Header 컴포넌트에 로그인 스타일 추가 / 서브 메뉴 추가

src/components/GroupFilter/GroupFilter.styles.ts, src/components/GroupFilter/index.tsx, src/components/GroupTripList/GroupTripList.styles.ts, src/components/GroupTripList/index.tsx, src/components/GroupUserInfo/index.tsx, src/components/TripCard/TripCard.styles.ts, src/pages/group/GroupMain/index.tsx
- 로딩 시 <Loader/> 컴포넌트 사용
- 필터 클릭 시 데이터 불러올 때 화면 흔들리는 문제 수정
- 그룹 페이지 검색바 기본 Input → @components/SearchBar
- 그룹 페이지 버튼 아이콘
- 버튼 사이즈 size=”sm”
- 버튼 아이콘 <RiEditFill /> , 필터 아이콘 <RiFilterLine /> <RiFilter3Fill />
- 카드 hover 시 transform scale → 1.01로 수정
- ‘마감된 일정입니다’ 버튼 색상 수정
- 작성 버튼과 검색 버튼이 가까이에 있지 않도록 여백 수정
- 페이지네이션 disabled 스타일 추가
=> Design : Group 페이지 및 TripCard 디자인 수정 

src/components/GroupUserInfo/GroupUserInfo.styles.ts, src/components/TripCard/TripCard.styles.ts, src/components/TripCard/index.tsx
=> Design : UserInfo 영역이 언제나 카드 가장 하단에 위치하도록 수정

src/components/Dropdown/index.tsx
- 그룹 모집 페이지에서 지역 드롭다운이 제대로 보이지 않는 문제를 수정했습니다
=> Fix : 그룹 모집 페이지에서 드롭다운 스타일이 제대로 보이지 않는 문제 수정

src/components/GroupMemberManagement/GroupMemberManagement.styles.ts, src/components/GroupMemberManagement/index.tsx, src/components/GroupUserInfo/GroupUserInfo.styles.ts, src/components/GroupUserInfo/index.tsx, src/components/TripCard/TripCard.styles.ts, src/components/TripCard/index.tsx, src/pages/mylounge/GroupManagement/GroupManagement.styles.ts, src/pages/mylounge/GroupManagement/index.tsx, src/utils/findCodeByLabel.ts
- 내가 그룹장일 때만 관리 버튼 컴포넌트가 보이도록 카드 컴포넌트를 리팩토링
- 같은 버튼을 클릭했을 때는 카드가 닫히지만, 다른 버튼을 클릭했을 때는 아이템만 바뀌도록 리팩토링
=> Feat : 마이라운지 그룹 관리 페이지

db.json, src/Router.tsx, src/apis/groupDetail.ts, src/components/GroupUserInfo/index.tsx, src/components/TripList/index.tsx, src/components/group/detail/GroupMemberStatus/GroupMemberStatus.styles.ts, src/components/group/detail/GroupMemberStatus/index.tsx, src/components/group/detail/GroupTitle/GroupTitle.styles.ts, src/components/group/detail/GroupTitle/index.tsx, src/components/group/detail/TripPlaceCard/TripPlaceCard.styles.ts, src/components/group/detail/TripPlaceCard/index.tsx, src/components/group/detail/TripPlaceList/TripPlaceList.styles.ts, src/components/group/detail/TripPlaceList/index.tsx, src/components/group/detail/TripTitle/TripTitle.styles.ts, src/components/group/detail/TripTitle/index.tsx, src/hooks/useGroup.tsx, src/pages/Home/index.tsx, src/pages/group/GroupDetail/GroupDetail.styles.ts, src/pages/group/GroupDetail/index.tsx, src/utils/dateUtil.ts
- 그룹 상세 데이터 mock data를 db.json 파일에 작성해서 불러옵니다.
- TripCard 클릭 시 해당 그룹 상세 페이지로 이동합니다.
- 현재 사용자의 지원 상태에 따라 '지원하기', '대기중', '지원취소' 버튼을 만들어야 합니다.
=> Feat: 그룹 상세 페이지 UI

src/apis/groupDetail.ts, src/components/TripCard/index.tsx, src/components/TripCardUserInfo/index.tsx, src/components/group/detail/GroupMemberStatus/index.tsx, src/pages/group/GroupDetail/index.tsx, src/utils/conversionGender.ts
- util/conversionGender 함수 작성해서 male->남성 female->여성으로 변환했습니다.
- age Type을 number로 지정했습니다. (임시)
- 나중에 확실해지면 다시 수정하는걸로 하겠습니다.
=> Refactor: 성별 한글로 변환하는 함수 작성

src/components/Header/index.tsx, src/components/HomeTripList/index.tsx, src/components/TripList/TripList.styles.ts, src/components/group/list/GroupTripList/GroupTripList.styles.ts, src/components/template/MainTemplate.tsx/MainTemplate.styles.ts, src/pages/group/GroupMain/GroupMain.styles.ts, src/pages/group/GroupMain/index.tsx
- Pagination이 MainTemplate의 가장 하단에 위치하도록 수정
- Header에서 '그룹찾기' 클릭 시 reload 하는 것이 아닌, paramsState를 초기화 하는 것으로 수정
=> Refactor: 그룹 페이지 UI 수정

src/apis/index.ts, src/components/Header/index.tsx, src/hooks/useAuth.tsx, src/recoil/userState.ts
- recoil-persist 로 관리했던 token을 localStorage에 담아서 저장 
- axios interceptor 안에서 사용하기 위함
=> Fix : 로그인 토큰을 recoil-persist에서 웹 스토리지로 관리 

src/components/Header/index.tsx, src/components/SearchBar/index.tsx, src/components/TripCard/TripCard.styles.ts, src/components/TripList/TripList.styles.ts, src/components/TripList/index.tsx, src/components/group/list/GroupFilter/index.tsx, src/components/group/list/GroupTripList/index.tsx, src/pages/group/GroupMain/index.tsx, src/utils/conversionArea.ts, src/utils/conversionGender.ts, src/utils/dateUtil.ts
- 광주 지역 추가했습니다.
- 그룹찾기 탭 클릭 시 reload가 아닌 paramsState를 변경하는 식으로 수정했습니다.
- d-day 계산하는 함수 수정했습니다.
- input: '2023-11-16' 과 같이 들어오는데, 여기에 + 'T00:00:00'을 추가함으로써 날짜만 비교하도록 변경했습니다.
- 페이지네이션에서 현재 페이지를 나타내는 forcePage 속성을 추가했습니다.
- 그룹 필터링 부분에서 다른 지역이나, 정렬상태 등을 선택할 때 page를 1로 set 해주도록 수정했습니다.
- SearchBar 컴포넌트에 defaultValue를 설정할 수 있도록 했습니다.
- pathname이 /group/recruit일 경우 빈 값을 보낼 수 없도록 했습니다.
- TripCard 내에 이미지의 높이를 min-height: 180px 으로 수정했습니다.
=> Refactor: 그룹 페이지 전반적으로 수정

src/apis/user.model.ts, src/apis/user.ts, src/hooks/useAuth.tsx, src/pages/user/Signup/index.tsx
- 회원가입 시 body로 값을 담아 보낼 수 있도록 수정
=> Fix : 회원가입 시 params가 아니라 body에 값을 넣어 보낼 수 있도록 수정

src/components/DropdownMenu/index.tsx, src/components/Header/Header.styles.ts, src/components/Header/index.tsx
=> Refactor : Header에 유저 정보 보여주도록 수정

src/apis/group.ts, src/apis/groupApply.ts, src/apis/groupDetail.ts, src/components/TripCard/index.tsx, src/components/TripCardUserInfo/TripCardUserInfo.styles.ts, src/components/TripCardUserInfo/index.tsx, src/components/group/detail/ApplyButton/index.tsx, src/components/group/detail/GroupMemberStatus/GroupMemberStatus.styles.ts, src/components/group/detail/GroupMemberStatus/index.tsx, src/components/group/detail/TripPlaceCard/TripPlaceCard.styles.ts, src/components/group/detail/TripPlaceCard/index.tsx, src/components/group/detail/TripPlaceList/TripPlaceList.styles.ts, src/components/group/detail/TripTitle/TripTitle.styles.ts, src/components/group/detail/TripTitle/index.tsx, src/components/group/list/GroupFilter/GroupFilter.styles.ts, src/components/group/list/GroupFilter/index.tsx, src/hooks/useGroup.tsx, src/pages/group/GroupDetail/GroupDetail.styles.ts, src/pages/group/GroupDetail/index.tsx, src/pages/group/GroupMain/index.tsx, src/utils/checkApplicationStatus.ts, src/utils/conversionGender.ts, src/utils/metersToKilometers.ts
- 상세 페이지 진입 시 여행 지도가 보이고, 각 카드 클릭 시 지도의 위치 변경
- 상세 정보 - 지도 데이터, 정보 데이터
=> Feat : 그룹 상세 페이지 

src/utils/dateUtil.ts
- 2023-12-2가 아니라 2023-12-02로 보내도록 함수 수정
=> Fix : 그룹모집 폼 제출 시 날짜 포맷 변경 

src/components/group/detail/TripPlaceCard/index.tsx, src/components/group/recruit/KakaoMap/index.tsx, src/pages/group/GroupDetail/index.tsx
- 그룹 상세 페이지 카드에 반복되는 함수에 useCallback을 써서 최적화
- 데이터를 불러오지 못했을 때, 혹은 데이터는 있지만 장소 데이터만 없을 때  errror 메세지를 보여줄 수 있도록 MapMarker 추가
=> Refactor : 그룹 상세 페이지 리팩토링 

src/components/Header/index.tsx, src/hooks/useGroup.tsx
- 수정 메뉴 클릭하면 수정페이지로 이동하도록 
- 드롭다운 클릭 시 내 프로필 수정 기능 추가
=> Feat : 누락된 드롭다운 메뉴 & 수정 메뉴 기능 추가 

src/Router.tsx, src/apis/mylounge.ts, src/components/Header/index.tsx, src/components/uploader/ProfileUploader/index.tsx, src/hooks/useFileUploader.tsx, src/hooks/useLounge.tsx, src/hooks/useUser.tsx, src/pages/mylounge/EditProfile/index.tsx
- 내 프로필 수정 기능 구현
- 프로필 수정 시, header와 로컬스로리지의 userInfo 갱신
=> Feat : 내 프로필 수정

src/components/HomeTripList/index.tsx, src/pages/Home/index.tsx
- 메인 페이지에 데이터 로딩 상태를 텍스트가 아닌 Loader 컴포넌트를 불러옴
- 컨테이너가 없는 상태에서 불러오니 너무 위쪽으로 붙어서 margin-top 적용했습니다.
- 메인 페이지에서 더 많은 일정보기 링크 클릭 시 params 초기화 작업
=> Design: 메인페이지 디자인 수정

src/components/HomeTripList/index.tsx
- 메인 페이지에서 데이터 없을 때 안내문구가 제대로 나오도록 수정
=> Chore : 메인 페이지 

src/components/common/uploader/FileUploader/index.tsx, src/components/group/card/TripCard/index.tsx, src/pages/Home/index.tsx
- 메인 페이지 배너와 TripCard에 이미지가 불러와지지 않았을 때 Layout Shift를 방지하고자 스켈레톤 UI를 적용하였습니다.
=> Feat : 스켈레톤 UI 적용

src/components/alarm/Alarm/Alarm.styles.ts, src/components/chat/ChatRoomCard/index.tsx
- 사용자가 입장해있는 채팅방에 대해서 새로운 채팅이 도착했다는 표시가 뜨는것을 useEffect 의존성 수정으로 해결했습니다.
- 읽지 않은 알림이 있는 경우 활성화 표시를 하는 아이콘을 12px에서 10px로 수정했습니다.
=> Refactor: 채팅 & 알림 수정

src/Router.tsx
카카오 콜백 페이지의 주소를 /oauth2/kakao로 변경했습니다. 
vercel에서 카카오 로그인이 가능합니다.
=> Refactor : 카카오 콜백 페이지 주소 변경
